import { ApiException } from '@loop/shared';
import type { ClusterResponse, ClusterParams } from '@loop/shared';
import { parseErrorResponse } from './parse-error-response';
import { API_BASE } from './config';

const PROTOBUF_MIME = 'application/x-protobuf';
const DEFAULT_TIMEOUT_MS = 30_000;

/**
 * Fetches map cluster data, requesting protobuf for bandwidth efficiency.
 * Falls back to JSON if the protobuf types are unavailable (during development
 * before `buf generate` has been run).
 *
 * @param params  viewport bounds + zoom
 * @param signal  optional AbortSignal — wired up with the timeout so a map
 *                component that unmounts (e.g. user pans quickly) can cancel
 *                in-flight fetches and avoid setState-after-unmount warnings.
 */
export async function fetchClusters(
  params: ClusterParams,
  signal?: AbortSignal,
): Promise<ClusterResponse> {
  const qs = new URLSearchParams({
    west: String(params.west),
    south: String(params.south),
    east: String(params.east),
    north: String(params.north),
    zoom: String(params.zoom),
  });

  // Compose caller signal with our timeout so either fires cancellation.
  const composed = signal
    ? AbortSignal.any([signal, AbortSignal.timeout(DEFAULT_TIMEOUT_MS)])
    : AbortSignal.timeout(DEFAULT_TIMEOUT_MS);

  let response: Response;
  try {
    response = await fetch(`${API_BASE}/api/clusters?${qs.toString()}`, {
      headers: { Accept: PROTOBUF_MIME },
      signal: composed,
    });
  } catch (err) {
    if (err instanceof DOMException && err.name === 'TimeoutError') {
      throw new ApiException(0, { code: 'TIMEOUT', message: 'Cluster request timed out' });
    }
    if (err instanceof DOMException && err.name === 'AbortError') {
      throw new ApiException(0, { code: 'TIMEOUT', message: 'Cluster request aborted' });
    }
    throw new ApiException(0, { code: 'NETWORK_ERROR', message: 'Cluster request failed' });
  }

  if (!response.ok) {
    // A2-1162: shared body-shape normalisation lives in
    // `parse-error-response.ts`. This file and `api-client.ts` used
    // to carry byte-for-byte copies of the coerce logic.
    const error = await parseErrorResponse(response);
    throw new ApiException(response.status, error);
  }

  const contentType = response.headers.get('Content-Type') ?? '';

  if (contentType.includes('x-protobuf')) {
    return decodeProtobufClusters(await response.arrayBuffer());
  }

  return response.json() as Promise<ClusterResponse>;
}

async function decodeProtobufClusters(buffer: ArrayBuffer): Promise<ClusterResponse> {
  // Proto types generated by `npx buf generate`. Import is dynamic so missing
  // module is caught at runtime and caller falls through to JSON.
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const { ProtobufClusterResponse } = (await import(
    '@loop/shared/src/proto/clustering_pb.js' as any
  )) as any;
  /* eslint-enable @typescript-eslint/no-explicit-any */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const msg = ProtobufClusterResponse.fromBinary(new Uint8Array(buffer)) as any;

  return {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    locationPoints: msg.locationPoints.map((p: any) => ({
      type: 'Feature' as const,
      properties: {
        cluster: false as const,
        merchantId: p.properties?.merchantId ?? '',
        mapPinUrl: p.properties?.mapPinUrl ?? '',
      },
      geometry: {
        type: 'Point' as const,
        coordinates: {
          longitude: p.geometry?.coordinates?.longitude ?? 0,
          latitude: p.geometry?.coordinates?.latitude ?? 0,
        },
      },
    })),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    clusterPoints: msg.clusterPoints.map((p: any, i: number) => ({
      type: 'Feature' as const,
      id: p.id ?? i,
      properties: {
        cluster: true as const,
        pointCount: p.properties?.pointCount ?? 0,
      },
      geometry: {
        type: 'Point' as const,
        coordinates: {
          longitude: p.geometry?.coordinates?.longitude ?? 0,
          latitude: p.geometry?.coordinates?.latitude ?? 0,
        },
      },
    })),
    total: msg.total,
    zoom: msg.zoom,
    loadedAt: Number(msg.loadedAt),
    bounds: {
      west: msg.bounds?.west ?? 0,
      south: msg.bounds?.south ?? 0,
      east: msg.bounds?.east ?? 0,
      north: msg.bounds?.north ?? 0,
    },
  };
}
