// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file proto/clustering.proto (package clustering, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file proto/clustering.proto.
 */
export const file_proto_clustering: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChZwcm90by9jbHVzdGVyaW5nLnByb3RvEgpjbHVzdGVyaW5nIjIKC0Nvb3JkaW5hdGVzEhEKCWxvbmdpdHVkZRgBIAEoARIQCghsYXRpdHVkZRgCIAEoASJGCghHZW9tZXRyeRIMCgR0eXBlGAEgASgJEiwKC2Nvb3JkaW5hdGVzGAIgASgLMhcuY2x1c3RlcmluZy5Db29yZGluYXRlcyJPChJMb2NhdGlvblByb3BlcnRpZXMSDwoHY2x1c3RlchgBIAEoCBITCgttZXJjaGFudF9pZBgCIAEoCRITCgttYXBfcGluX3VybBgDIAEoCSI5ChFDbHVzdGVyUHJvcGVydGllcxIPCgdjbHVzdGVyGAEgASgIEhMKC3BvaW50X2NvdW50GAIgASgFInkKDUxvY2F0aW9uUG9pbnQSDAoEdHlwZRgBIAEoCRIyCgpwcm9wZXJ0aWVzGAIgASgLMh4uY2x1c3RlcmluZy5Mb2NhdGlvblByb3BlcnRpZXMSJgoIZ2VvbWV0cnkYAyABKAsyFC5jbHVzdGVyaW5nLkdlb21ldHJ5IoMBCgxDbHVzdGVyUG9pbnQSDAoEdHlwZRgBIAEoCRIxCgpwcm9wZXJ0aWVzGAIgASgLMh0uY2x1c3RlcmluZy5DbHVzdGVyUHJvcGVydGllcxImCghnZW9tZXRyeRgDIAEoCzIULmNsdXN0ZXJpbmcuR2VvbWV0cnkSCgoCaWQYBCABKAUiQgoGQm91bmRzEgwKBHdlc3QYASABKAESDQoFc291dGgYAiABKAESDAoEZWFzdBgDIAEoARINCgVub3J0aBgEIAEoASLTAQoXUHJvdG9idWZDbHVzdGVyUmVzcG9uc2USMgoPbG9jYXRpb25fcG9pbnRzGAEgAygLMhkuY2x1c3RlcmluZy5Mb2NhdGlvblBvaW50EjAKDmNsdXN0ZXJfcG9pbnRzGAIgAygLMhguY2x1c3RlcmluZy5DbHVzdGVyUG9pbnQSDQoFdG90YWwYAyABKAUSDAoEem9vbRgEIAEoBRIRCglsb2FkZWRfYXQYBSABKAMSIgoGYm91bmRzGAYgASgLMhIuY2x1c3RlcmluZy5Cb3VuZHNCBFoCLi9iBnByb3RvMw',
  );

/**
 * Geographic coordinates
 *
 * @generated from message clustering.Coordinates
 */
export type Coordinates = Message<'clustering.Coordinates'> & {
  /**
   * @generated from field: double longitude = 1;
   */
  longitude: number;

  /**
   * @generated from field: double latitude = 2;
   */
  latitude: number;
};

/**
 * Describes the message clustering.Coordinates.
 * Use `create(CoordinatesSchema)` to create a new message.
 */
export const CoordinatesSchema: GenMessage<Coordinates> =
  /*@__PURE__*/
  messageDesc(file_proto_clustering, 0);

/**
 * Geometry for GeoJSON-like structure
 *
 * @generated from message clustering.Geometry
 */
export type Geometry = Message<'clustering.Geometry'> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: clustering.Coordinates coordinates = 2;
   */
  coordinates?: Coordinates;
};

/**
 * Describes the message clustering.Geometry.
 * Use `create(GeometrySchema)` to create a new message.
 */
export const GeometrySchema: GenMessage<Geometry> =
  /*@__PURE__*/
  messageDesc(file_proto_clustering, 1);

/**
 * Properties for individual location points
 *
 * @generated from message clustering.LocationProperties
 */
export type LocationProperties = Message<'clustering.LocationProperties'> & {
  /**
   * @generated from field: bool cluster = 1;
   */
  cluster: boolean;

  /**
   * @generated from field: string merchant_id = 2;
   */
  merchantId: string;

  /**
   * @generated from field: string map_pin_url = 3;
   */
  mapPinUrl: string;
};

/**
 * Describes the message clustering.LocationProperties.
 * Use `create(LocationPropertiesSchema)` to create a new message.
 */
export const LocationPropertiesSchema: GenMessage<LocationProperties> =
  /*@__PURE__*/
  messageDesc(file_proto_clustering, 2);

/**
 * Properties for cluster points
 *
 * @generated from message clustering.ClusterProperties
 */
export type ClusterProperties = Message<'clustering.ClusterProperties'> & {
  /**
   * @generated from field: bool cluster = 1;
   */
  cluster: boolean;

  /**
   * @generated from field: int32 point_count = 2;
   */
  pointCount: number;
};

/**
 * Describes the message clustering.ClusterProperties.
 * Use `create(ClusterPropertiesSchema)` to create a new message.
 */
export const ClusterPropertiesSchema: GenMessage<ClusterProperties> =
  /*@__PURE__*/
  messageDesc(file_proto_clustering, 3);

/**
 * Individual location point
 *
 * @generated from message clustering.LocationPoint
 */
export type LocationPoint = Message<'clustering.LocationPoint'> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: clustering.LocationProperties properties = 2;
   */
  properties?: LocationProperties;

  /**
   * @generated from field: clustering.Geometry geometry = 3;
   */
  geometry?: Geometry;
};

/**
 * Describes the message clustering.LocationPoint.
 * Use `create(LocationPointSchema)` to create a new message.
 */
export const LocationPointSchema: GenMessage<LocationPoint> =
  /*@__PURE__*/
  messageDesc(file_proto_clustering, 4);

/**
 * Cluster point
 *
 * @generated from message clustering.ClusterPoint
 */
export type ClusterPoint = Message<'clustering.ClusterPoint'> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: clustering.ClusterProperties properties = 2;
   */
  properties?: ClusterProperties;

  /**
   * @generated from field: clustering.Geometry geometry = 3;
   */
  geometry?: Geometry;

  /**
   * @generated from field: int32 id = 4;
   */
  id: number;
};

/**
 * Describes the message clustering.ClusterPoint.
 * Use `create(ClusterPointSchema)` to create a new message.
 */
export const ClusterPointSchema: GenMessage<ClusterPoint> =
  /*@__PURE__*/
  messageDesc(file_proto_clustering, 5);

/**
 * Bounding box
 *
 * @generated from message clustering.Bounds
 */
export type Bounds = Message<'clustering.Bounds'> & {
  /**
   * @generated from field: double west = 1;
   */
  west: number;

  /**
   * @generated from field: double south = 2;
   */
  south: number;

  /**
   * @generated from field: double east = 3;
   */
  east: number;

  /**
   * @generated from field: double north = 4;
   */
  north: number;
};

/**
 * Describes the message clustering.Bounds.
 * Use `create(BoundsSchema)` to create a new message.
 */
export const BoundsSchema: GenMessage<Bounds> = /*@__PURE__*/ messageDesc(file_proto_clustering, 6);

/**
 * Main clustering response
 *
 * @generated from message clustering.ProtobufClusterResponse
 */
export type ProtobufClusterResponse = Message<'clustering.ProtobufClusterResponse'> & {
  /**
   * @generated from field: repeated clustering.LocationPoint location_points = 1;
   */
  locationPoints: LocationPoint[];

  /**
   * @generated from field: repeated clustering.ClusterPoint cluster_points = 2;
   */
  clusterPoints: ClusterPoint[];

  /**
   * @generated from field: int32 total = 3;
   */
  total: number;

  /**
   * @generated from field: int32 zoom = 4;
   */
  zoom: number;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 loaded_at = 5;
   */
  loadedAt: bigint;

  /**
   * @generated from field: clustering.Bounds bounds = 6;
   */
  bounds?: Bounds;
};

/**
 * Describes the message clustering.ProtobufClusterResponse.
 * Use `create(ProtobufClusterResponseSchema)` to create a new message.
 */
export const ProtobufClusterResponseSchema: GenMessage<ProtobufClusterResponse> =
  /*@__PURE__*/
  messageDesc(file_proto_clustering, 7);
