import pino from 'pino';
import { config } from './config/index.js';

// Pino redaction paths — ADR 016, ADR 031, ADR 036, ADR 044, ADR 013, ADR 030, A4-040, A4-039
export const REDACT_PATHS: readonly string[] = [
  'authorization',
  'Authorization',
  '*.authorization',
  '*.Authorization',
  '*.*.authorization',
  '*.*.Authorization',
  'req.headers.authorization',
  'req.headers.Authorization',
  'req.headers.cookie',
  'headers.authorization',
  'headers.Authorization',
  'headers.cookie',
  '*.cookie',
  'accessToken',
  'refreshToken',
  '*.accessToken',
  '*.refreshToken',
  '*.*.accessToken',
  '*.*.refreshToken',
  'otp',
  'code',
  '*.otp',
  'password',
  '*.password',
  'apiKey',
  'apiSecret',
  '*.apiKey',
  '*.apiSecret',
  '*.*.apiKey',
  '*.*.apiSecret',
  'X-Api-Key',
  'X-Api-Secret',
  '*.X-Api-Key',
  '*.X-Api-Secret',
  'secret',
  'privateKey',
  'secretKey',
  'seedPhrase',
  'mnemonic',
  '*.secret',
  '*.privateKey',
  '*.secretKey',
  '*.seedPhrase',
  '*.mnemonic',
  'operatorSecret',
  '*.operatorSecret',
  'LOOP_STELLAR_OPERATOR_SECRET',
  'LOOP_STELLAR_OPERATOR_SECRET_PREVIOUS',
  '*.LOOP_STELLAR_OPERATOR_SECRET',
  '*.LOOP_STELLAR_OPERATOR_SECRET_PREVIOUS',
  'LOOP_STELLAR_USDLOOP_ISSUER_SECRET',
  'LOOP_STELLAR_GBPLOOP_ISSUER_SECRET',
  'LOOP_STELLAR_EURLOOP_ISSUER_SECRET',
  '*.LOOP_STELLAR_USDLOOP_ISSUER_SECRET',
  '*.LOOP_STELLAR_GBPLOOP_ISSUER_SECRET',
  '*.LOOP_STELLAR_EURLOOP_ISSUER_SECRET',
  'issuerSecret',
  '*.issuerSecret',
  'channelSecret',
  '*.channelSecret',
  'LOOP_STELLAR_PAYOUT_CHANNEL_SECRETS',
  '*.LOOP_STELLAR_PAYOUT_CHANNEL_SECRETS',
  'LOOP_JWT_SIGNING_KEY',
  'LOOP_JWT_SIGNING_KEY_PREVIOUS',
  '*.LOOP_JWT_SIGNING_KEY',
  '*.LOOP_JWT_SIGNING_KEY_PREVIOUS',
  'GIFT_CARD_API_KEY',
  'GIFT_CARD_API_SECRET',
  '*.GIFT_CARD_API_KEY',
  '*.GIFT_CARD_API_SECRET',
  'RESEND_API_KEY',
  '*.RESEND_API_KEY',
  'secretAccessKey',
  '*.secretAccessKey',
  '*.*.secretAccessKey',
  'AWS_SECRET_ACCESS_KEY',
  '*.AWS_SECRET_ACCESS_KEY',
  'PRIVY_APP_SECRET',
  '*.PRIVY_APP_SECRET',
  'appSecret',
  '*.appSecret',
  '*.*.appSecret',
  'DATABASE_URL',
  '*.DATABASE_URL',
  'SENTRY_DSN',
  '*.SENTRY_DSN',
  'DISCORD_WEBHOOK_ORDERS',
  'DISCORD_WEBHOOK_MONITORING',
  'DISCORD_WEBHOOK_ADMIN_AUDIT',
  '*.DISCORD_WEBHOOK_ORDERS',
  '*.DISCORD_WEBHOOK_MONITORING',
  '*.DISCORD_WEBHOOK_ADMIN_AUDIT',
  'idempotencyKey',
  '*.idempotencyKey',
  '*.*.idempotencyKey',
  'idempotency-key',
  '*.idempotency-key',
  '*.*.idempotency-key',
  'Idempotency-Key',
  '*.Idempotency-Key',
  '*.*.Idempotency-Key',
];

const basePinoOptions = {
  level: config.server.logLevel,
  base: { service: 'loop-backend', env: config.env },
  redact: { paths: [...REDACT_PATHS], censor: '[REDACTED]' },
};

export const logger =
  config.env === 'development'
    ? pino({
        ...basePinoOptions,
        transport: { target: 'pino-pretty', options: { colorize: true } },
      })
    : pino(basePinoOptions);
