import type { Context } from 'hono';
import { clusterLocations } from './algorithm.js';
import { getLocations } from './data-store.js';
import { logger } from '../logger.js';

const PROTOBUF_MIME = 'application/x-protobuf';

/**
 * GET /api/clusters
 *
 * Query params: west, south, east, north (float), zoom (int)
 * Responds with protobuf when Accept header includes application/x-protobuf,
 * otherwise JSON.
 */
export async function clustersHandler(c: Context): Promise<Response> {
  const log = logger.child({ handler: 'clusters' });

  const west = parseFloat(c.req.query('west') ?? '');
  const south = parseFloat(c.req.query('south') ?? '');
  const east = parseFloat(c.req.query('east') ?? '');
  const north = parseFloat(c.req.query('north') ?? '');
  const rawZoom = parseInt(c.req.query('zoom') ?? '', 10);

  if ([west, south, east, north, rawZoom].some((v) => isNaN(v))) {
    return c.json(
      { code: 'VALIDATION_ERROR', message: 'west, south, east, north, zoom are required' },
      400,
    );
  }

  const zoom = Math.max(0, Math.min(28, rawZoom));

  // Expand bbox by 50% for pre-loading — matching Go reference behaviour
  const latBuf = (north - south) * 0.5;
  const lngBuf = (east - west) * 0.5;
  const expandedBounds = {
    west: west - lngBuf,
    south: south - latBuf,
    east: east + lngBuf,
    north: north + latBuf,
  };

  const { locations, loadedAt } = getLocations();

  // Filter to expanded bounds
  const filtered = locations.filter(
    (loc) =>
      loc.latitude >= expandedBounds.south &&
      loc.latitude <= expandedBounds.north &&
      loc.longitude >= expandedBounds.west &&
      loc.longitude <= expandedBounds.east,
  );

  const originalBounds = { west, south, east, north };
  const start = Date.now();
  const result = clusterLocations(filtered, originalBounds, zoom);
  log.debug(
    {
      zoom,
      input: filtered.length,
      locationPoints: result.locationPoints.length,
      clusterPoints: result.clusterPoints.length,
      ms: Date.now() - start,
    },
    'Clustering complete',
  );

  const wantsProtobuf = c.req.header('Accept')?.includes(PROTOBUF_MIME) ?? false;

  if (wantsProtobuf) {
    // Lazy-import generated protobuf types to avoid hard startup dependency
    // before buf generate has been run.
    try {
      // Proto types are generated by `npx buf generate`. The import will fail
      // gracefully before generation — server falls back to JSON.
      /* eslint-disable @typescript-eslint/no-explicit-any */
      const { ProtobufClusterResponse } = (await import(
        '@loop/shared/src/proto/clustering_pb.js' as any
      )) as any;
      /* eslint-enable @typescript-eslint/no-explicit-any */
      const msg = new ProtobufClusterResponse({
        locationPoints: result.locationPoints.map((p) => ({
          type: p.type,
          properties: {
            cluster: false,
            merchantId: p.properties.merchantId,
            mapPinUrl: p.properties.mapPinUrl,
          },
          geometry: {
            type: 'Point',
            coordinates: {
              longitude: p.geometry.coordinates.longitude,
              latitude: p.geometry.coordinates.latitude,
            },
          },
        })),
        clusterPoints: result.clusterPoints.map((p) => ({
          type: p.type,
          id: p.id,
          properties: { cluster: true, pointCount: p.properties.pointCount },
          geometry: {
            type: 'Point',
            coordinates: {
              longitude: p.geometry.coordinates.longitude,
              latitude: p.geometry.coordinates.latitude,
            },
          },
        })),
        total: filtered.length,
        zoom,
        loadedAt: BigInt(Math.floor(loadedAt / 1000)),
        bounds: { west, south, east, north },
      });

      const bytes = msg.toBinary();
      return new Response(bytes, {
        headers: { 'Content-Type': PROTOBUF_MIME },
      });
    } catch {
      // Protobuf types not yet generated — fall through to JSON
      log.warn('Protobuf types not found, falling back to JSON');
    }
  }

  return c.json({
    locationPoints: result.locationPoints,
    clusterPoints: result.clusterPoints,
    total: filtered.length,
    zoom,
    loadedAt: Math.floor(loadedAt / 1000),
    bounds: originalBounds,
  });
}
